training_samples: 15
parent_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c"
activation_layers:
 - "IT"

max_permutations: 50 # How many of the possible training sample permutations to use (e.g., 16x16 = 256)