training_samples: 15
parent_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c+b/units/IT"
activation_layers:
 - "IT"
max_permutations: 12 # How many of the possible training sample permutations to use (e.g., 16x16 = 256)