image_dir: "stimuli"
layer_name: "IT"
layer_path: "module._modules.IT._modules.output" #"module._modules.V1._modules.output" READ from IT atm
n_bootstrap: 10000
model_source: "cornet"
model_repo: "-"
model_name: "cornet_rt"
model_weights: "" # torch.hub weights (not necesssary for cornet models). Leave empty for untrained.
pretrained: True
vmax: 0.4
mc_permutations: 200 # How many monte carlo permutations on damage to perform. Use 21 as in Haupt et al., 2024?
model_time_steps: 5 # recurrent

layer_paths_to_damage: 
  - "module._modules.IT"
apply_to_all_layers: False
include_bias: False
only_conv: False

# groupnorm_scaling damage parameters
groupnorm_scaling: 
  - 1
  - 10
  - -0.1
  
# Masking damage parameters
manipulation_method: "masking"
masking_level: "connections"  # "connections" or "units"
fraction_to_mask: # Start, N (int), interval [start,N*interval]
  - 0
  - 0
  - 0.05

# Noise damage parameters
noise_levels: # Start, N (int), interval [start, N*interval]
  - 0
  - 0
  - 0.1