model_source: cornet        # one of: cornet | pytorch_hub
model_name: cornet_rt       # model name
model_weights: ""   # 
model_time_steps: 5         # only needed for CORnet models

data_root: categ_images # folder containing four subfolders (animals, faces, objects, places), 20 images each

batch_size: 8           # how many images to process at once

out_dir: unit_selectivity
metrics: [mannwhitneyu, hedgesg]
pretrained: false