# analyse_it2v1.yaml
selectivity_csv_dir: unit_selectivity
category: faces
top_unit_selection: percentage
top_frac: [0.01, 0.05, 0.1]
n_random_repeats: 100
category_images: categ_images_testset/faces
image_categories: [places, animals, objects]
max_images: 64
pixels_per_degree: None
output_dir: it2v1_analysis
gaussian_sigma: 0
model:
  source: cornet
  name: cornet_rt
  weights: pretrained
  time_steps: 5
  device: auto
