subdir: "cornet_rt5/"
tasks:
  - function: damage_type_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c_std_noise/"
      layer: "V1"
      damage_types: ["noise","connections"]
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0
  - function: damage_type_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c_std_noise/"
      layer: "V2"
      damage_types: ["noise","connections"]
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0
  - function: damage_type_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c_std_noise/"
      layer: "V4"
      damage_types: ["noise","connections"]
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0
  - function: damage_type_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c_std_noise/"
      layer: "IT"
      damage_types: ["noise","connections"]
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0