subdir: "cornet_rt5_c/"
tasks:
  - function: plot_categ_differences
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V1","IT"]
      activations_layers: ["IT"]
      damage_type: "noise"
      verbose: 0
      damage_levels: ["0.0","0.5","1.0"]
      comparison: True
  - function: plot_categ_differences
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V1","IT"]
      activations_layers: ["IT"]
      damage_type: "connections"
      verbose: 0
      damage_levels: ["0.0","0.2","0.5"]
      comparison: True
  - function: plot_categ_differences
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V1","V2","V4"]
      activations_layers: ["V4"]
      damage_type: "connections"
      verbose: 0
      damage_levels: ["0","0.2","0.5"]
      comparison: True
  - function: plot_categ_differences
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V1","V2","V4"]
      activations_layers: ["V4"]
      damage_type: "noise"
      verbose: 0
      damage_levels: ["0","0.5","1"]
      comparison: True