subdir: "cornet_rt5_c/"
tasks:
 

  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_all/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "eccentricity_gradual_band0.00-0.30"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      data_type: "selectivity"
      flip_x_axis: False
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.05
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_all/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "eccentricity_gradual_band0.00-0.30"
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0
      percentage: True 
      data_type: "selectivity"
      flip_x_axis: False
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.05
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_all/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "eccentricity_gradual_band0.00-0.50"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      data_type: "selectivity"
      flip_x_axis: False
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.05
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_all/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "eccentricity_gradual_band0.00-0.50"
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      data_type: "selectivity"
      flip_x_axis: False
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.05
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_all/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "eccentricity_gradual_band0.00-0.80"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      data_type: "selectivity"
      flip_x_axis: False
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.05
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_all/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "eccentricity_gradual_band0.00-0.80"
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      data_type: "selectivity"
      flip_x_axis: False
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.05
 
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_all/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "eccentricity_gradual_band0.00-0.30"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      data_type: "selectivity"
      flip_x_axis: False
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_all/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "eccentricity_gradual_band0.00-0.30"
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      data_type: "selectivity"
      flip_x_axis: False
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_all/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "eccentricity_gradual_band0.00-0.50"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      data_type: "selectivity"
      flip_x_axis: False
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_all/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "eccentricity_gradual_band0.00-0.50"
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      data_type: "selectivity"
      flip_x_axis: False
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_all/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "eccentricity_gradual_band0.00-0.80"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      data_type: "selectivity"
      flip_x_axis: False
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_all/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "eccentricity_gradual_band0.00-0.80"
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      data_type: "selectivity"
      flip_x_axis: False
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.01
 