subdir: "cornet_rt5_c/"
tasks:
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      ylim: [-0.05,0.5]
      data_type: "selectivity"
      scatter: True
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      ylim: [0.45,1.05]
      data_type: "svm_15"
      scatter: True
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      ylim: [-0.05,0.5]
      data_type: "selectivity"
      scatter: True
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      ylim: [0.45,1.05]
      data_type: "svm_15"
      scatter: True
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V2"]
      activations_layers: ["IT"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      ylim: [-0.05,0.5]
      data_type: "selectivity"
      scatter: True
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V2"]
      activations_layers: ["IT"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      ylim: [0.45,1.05]
      data_type: "svm_15"
      scatter: True