subdir: "cornet_rt5_c/"
tasks:
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_all/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "eccentricity_gradual_band0.70-1.00"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 2
      percentage: True
      data_type: "selectivity"
      flip_x_axis: False
      plot_dir: "plots/cornet_rt5_c/within-between"
      selectivity_fraction: 0.05
