subdir: "cornet_rt5_c/"
tasks:
  - function: plot_categ_differences
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["IT"]
      activations_layers: ["IT"]
      damage_type: "noise"
      verbose: 0
      damage_levels: ["0.0","1.8"]
      comparison: True
      scatter: True
      ylim: [0,1.2]
  - function: plot_categ_differences
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V4"]
      activations_layers: ["IT"]
      damage_type: "noise"
      verbose: 0
      damage_levels: ["0.0","1.4"]
      comparison: True
      scatter: True
      ylim: [0,1.2]
  - function: plot_categ_differences
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V2"]
      activations_layers: ["IT"]
      damage_type: "noise"
      verbose: 0
      damage_levels: ["0.0","1.3"]
      comparison: True
      scatter: True
      ylim: [0,1.2]
  - function: plot_categ_differences
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "noise"
      verbose: 0
      damage_levels: ["0.0","1.15"]
      comparison: True
      scatter: True
      ylim: [0,1.2]
  - function: plot_categ_differences
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["IT"]
      activations_layers: ["IT"]
      damage_type: "connections"
      verbose: 0
      damage_levels: ["0.0","0.7"]
      comparison: True
      scatter: True
      ylim: [0,1.2]
  - function: plot_categ_differences
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "connections"
      verbose: 0
      damage_levels: ["0.0","0.25"]
      comparison: True
      scatter: True
      ylim: [0,1.2]
  - function: plot_categ_differences
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V2"]
      activations_layers: ["IT"]
      damage_type: "connections"
      verbose: 0
      damage_levels: ["0.0","0.4"]
      comparison: True
      scatter: True
      ylim: [0,1.2]
  - function: plot_categ_differences
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V4"]
      activations_layers: ["IT"]
      damage_type: "connections"
      verbose: 0
      damage_levels: ["0.0","0.55"]
      comparison: True
      scatter: True
      ylim: [0,1.2]