subdir: "cornet_rt5_c/"
tasks:
  - function: plot_categ_differences
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["IT"]
      activations_layers: ["IT"]
      damage_type: "connections"
      verbose: 0
      damage_levels: ["0.0","3.0"]
      comparison: True
      scatter: True
      ylim: [0.45,1.05]
      data_type: "svm_15"
  - function: plot_categ_differences
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V4"]
      activations_layers: ["IT"]
      damage_type: "noise"
      verbose: 0
      damage_levels: ["0.0","3.0"]
      comparison: False
      scatter: True
      ylim: [0.45,1.05]
      data_type: "svm_15"
  - function: plot_categ_differences
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V2"]
      activations_layers: ["IT"]
      damage_type: "noise"
      verbose: 0
      damage_levels: ["0.0","3.0"]
      comparison: False
      scatter: True
      ylim: [0.45,1.05]
      data_type: "svm_15"
  - function: plot_categ_differences
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V4"]
      activations_layers: ["IT"]
      damage_type: "connections"
      verbose: 0
      damage_levels: ["0.0","0.8"]
      comparison: True
      scatter: True
      ylim: [0.45,1.05]
      data_type: "svm_15"
  - function: plot_categ_differences
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V2"]
      activations_layers: ["IT"]
      damage_type: "connections"
      verbose: 0
      damage_levels: ["0.0","0.8"]
      comparison: True
      scatter: True
      ylim: [0.45,1.05]
      data_type: "svm_15"