subdir: "cornet_rt5_c/"
tasks:
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V1","V2","V4","IT"]
      activations_layers: ["IT"]
      damage_type: "noise"
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0
      ylim: [0,0.18]
      data_type: "selectivity"
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V1","V2","V4","IT"]
      activations_layers: ["IT"]
      damage_type: "connections"
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0
      ylim: [0,0.18]
      data_type: "selectivity"
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V1","V2","V4"]
      activations_layers: ["V4"]
      damage_type: "noise"
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0
      ylim: [0,0.18]
      data_type: "selectivity"
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V1","V2","V4"]
      activations_layers: ["V4"]
      damage_type: "connections"
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0
      ylim: [0,0.18]
      data_type: "selectivity"
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "noise"
      categories: ["animal","object","face","scene"]
      metric: "observed_difference"
      verbose: 0
      ylim: [0,0.18]
      data_type: "selectivity"
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "connections"
      categories: ["animal","object","face","scene"]
      metric: "observed_difference"
      verbose: 0
      ylim: [0,0.18]
      data_type: "selectivity"