subdir: "cornet_rt5_c/"
tasks:
  - function: "categ_corr_lineplot"
    parameters:
      damage_layers: ["V1","V2","V4","IT"]
      activations_layers: ["IT"]
      damage_type: "connections"
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      categories: ["total"]
      verbose: 0
      data_type: "svm_15"
      ylim: [0.45,1.05]
  - function: "categ_corr_lineplot"
    parameters:
      damage_layers: ["V1","V2","V4","IT"]
      activations_layers: ["IT"]
      damage_type: "noise"
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      categories: ["total"]
      verbose: 0
      data_type: "svm_15"
      ylim: [0.45,1.05]
  - function: "categ_corr_lineplot"
    parameters:
      damage_layers: ["V1","V2","V4"]
      activations_layers: ["V4"]
      damage_type: "connections"
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      categories: ["total"]
      verbose: 0
      data_type: "svm_15"
      ylim: [0.45,1.05]
  - function: "categ_corr_lineplot"
    parameters:
      damage_layers: ["V1","V2","V4"]
      activations_layers: ["V4"]
      damage_type: "noise"
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      categories: ["total"]
      verbose: 0
      data_type: "svm_15"
      ylim: [0.45,1.05]
  - function: "categ_corr_lineplot"
    parameters:
      damage_layers: ["V1","V2"]
      activations_layers: ["V2"]
      damage_type: "connections"
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      categories: ["total"]
      verbose: 0
      data_type: "svm_15"
      ylim: [0.45,1.05]
  - function: "categ_corr_lineplot"
    parameters:
      damage_layers: ["V1","V2"]
      activations_layers: ["V2"]
      damage_type: "noise"
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      categories: ["total"]
      verbose: 0
      data_type: "svm_15"
      ylim: [0.45,1.05]
  - function: "categ_corr_lineplot"
    parameters:
      damage_layers: ["V1"]
      activations_layers: ["V1"]
      damage_type: "connections"
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      categories: ["total"]
      verbose: 0
      data_type: "svm_15"
      ylim: [0.45,1.05]
  - function: "categ_corr_lineplot"
    parameters:
      damage_layers: ["V1"]
      activations_layers: ["V1"]
      damage_type: "noise"
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      categories: ["total"]
      verbose: 0
      data_type: "svm_15"
      ylim: [0.45,1.05]