subdir: "cornet_rt5_c/"
tasks:
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-15,105]
      data_type: "selectivity"
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [60,105]
      data_type: "svm_15"
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V2"]
      activations_layers: ["IT"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-15,105]
      data_type: "selectivity"
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V2"]
      activations_layers: ["IT"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [60,105]
      data_type: "svm_15"
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V4"]
      activations_layers: ["IT"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-15,105]
      data_type: "selectivity"
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["V4"]
      activations_layers: ["IT"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [60,105]
      data_type: "svm_15"
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["IT"]
      activations_layers: ["IT"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-15,105]
      data_type: "selectivity"
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt5_c/"
      damage_layers: ["IT"]
      activations_layers: ["IT"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      data_type: "svm_15"
      percentage: True
      ylim: [60,105]