subdir: "cornet_s5_c/"
tasks:
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_s5_c/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-15,105]
      data_type: "selectivity"
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_s5_c/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-15,105]
      data_type: "selectivity"
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_s5_c/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.1,1]
      data_type: "selectivity"
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_s5_c/"
      damage_layers: ["V1"]
      activations_layers: ["IT"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.1,1]
      data_type: "selectivity"


  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_s5_c/"
      damage_layers: ["V2"]
      activations_layers: ["IT"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-15,105]
      data_type: "selectivity"
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_s5_c/"
      damage_layers: ["V2"]
      activations_layers: ["IT"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-15,105]
      data_type: "selectivity"
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_s5_c/"
      damage_layers: ["V2"]
      activations_layers: ["IT"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.1,1]
      data_type: "selectivity"
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_s5_c/"
      damage_layers: ["V2"]
      activations_layers: ["IT"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.1,1]
      data_type: "selectivity"


  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_s5_c/"
      damage_layers: ["V4"]
      activations_layers: ["IT"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-15,105]
      data_type: "selectivity"
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_s5_c/"
      damage_layers: ["V4"]
      activations_layers: ["IT"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-15,105]
      data_type: "selectivity"
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_s5_c/"
      damage_layers: ["V4"]
      activations_layers: ["IT"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.1,1]
      data_type: "selectivity"
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_s5_c/"
      damage_layers: ["V4"]
      activations_layers: ["IT"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.1,1]
      data_type: "selectivity"


  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_s5_c/"
      damage_layers: ["IT"]
      activations_layers: ["IT"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-15,105]
      data_type: "selectivity"
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_s5_c/"
      damage_layers: ["IT"]
      activations_layers: ["IT"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: True
      ylim: [-15,105]
      data_type: "selectivity"
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_s5_c/"
      damage_layers: ["IT"]
      activations_layers: ["IT"]
      damage_type: "noise"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.1,1]
      data_type: "selectivity"
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_s5_c/"
      damage_layers: ["IT"]
      activations_layers: ["IT"]
      damage_type: "connections"
      categories: ["animal","face","object","place"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.1,1]
      data_type: "selectivity"


  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_s5_c/"
      damage_layers: ["V1","V2","V4","IT"]
      activations_layers: ["IT"]
      damage_type: "connections"
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.05,0.25]
      data_type: "selectivity"
  - function: categ_corr_lineplot
    parameters:
      main_dir: "data/haupt_stim_activ/damaged/cornet_s5_c/"
      damage_layers: ["V1","V2","V4","IT"]
      activations_layers: ["IT"]
      damage_type: "noise"
      categories: ["total"]
      metric: "observed_difference"
      verbose: 0
      percentage: False
      ylim: [-0.05,0.25]
      data_type: "selectivity"
