image_dir: "stimuli"
layer_name: "V1"
layer_path: 
 - "module._modules.IT._modules.output"
model_source: "cornet"
model_repo: "-"
model_name: "cornet_rt"
model_weights: "" # torch.hub weights (not necesssary for cornet models). Leave empty for untrained.
pretrained: True
model_time_steps: 4
mc_permutations: 200 # How many monte carlo permutations on damage to perform. Use 21 as in Haupt et al., 2024?

layer_paths_to_damage: 
  - "module._modules.V1"
apply_to_all_layers: False
include_bias: False
only_conv: True

# Masking damage parameters
manipulation_method: "masking"
masking_level: "connections"  # "connections" or "units"
fraction_to_mask: # Start, N (int), interval [start,N*interval]
  - 0
  - 21
  - 0.05

# Noise damage parameters
noise_levels: # Start, N (int), interval [start, N*interval]
  - 0
  - 31
  - 0.1



# groupnorm_scaling damage parameters
groupnorm_scaling: 
  - 1
  - 0
  - -0.05
groupnorm_scaling_targets: ["conv"]
gain_control_noise: 0.5
# Masking damage parameters

ecc_fraction_to_mask:
  - 0
  - 0
  - 0.05