image_dir: "stimuli"
layer_name: "block4"
layer_path: 
 - "features.12"
model_source: "pytorch_hub"
model_repo: pytorch/vision
model_name: "alexnet"
model_weights: "DEFAULT" # torch.hub weights (not necesssary for cornet models). Leave empty for untrained.
pretrained: True

mc_permutations: 200 # How many monte carlo permutations on damage to perform. Use 21 as in Haupt et al., 2024?

layer_paths_to_damage: 
  - "features.8"
apply_to_all_layers: False
include_bias: True
only_conv: True

# Masking damage parameters
manipulation_method: "masking"
masking_level: "units"  # "connections" or "units"
fraction_to_mask: # Start, N (int), interval [start,N*interval]
  - 0
  - 21
  - 0.05

# Noise damage parameters
noise_levels: # Start, N (int), interval [start, N*interval]
  - 0
  - 0
  - 0.1




# groupnorm_scaling damage parameters
groupnorm_scaling: 
  - 1
  - 0
  - -0.05
groupnorm_scaling_targets: ["conv"]
gain_control_noise: 0.5
# Masking damage parameters

ecc_fraction_to_mask:
  - 0
  - 0
  - 0.05