image_dir: "stimuli"
layer_name: "V1"
layer_path: "module._modules.V1._modules.pool"
n_bootstrap: 10000
model_source: "cornet"
model_repo: "-"
model_name: "cornet_z"
model_weights: "" # torch.hub weights (not necesssary for cornet models). Leave empty for untrained.
pretrained: True
vmax: 0.4