tasks:
  - function: "pair_corr_scatter_subplots"
    parameters:
      layers: ["V1", "V2", "IT"]
      damage_type: "connections"
      damage_levels: ["0.0","0.1","0.2", "0.5", "0.9"] # List
      image1: "animal1"
      image2: "animal5"
      n_permutations: 5
      main_dir: "data/haupt_stim_activ/damaged/cornet_rt/"
      verbose: 0
      lower_limit: 0
      use_log_scale: false